units:
  # Key and keycap measures
  kx: u # spacing between key centers (X-axis)
  ky: u # spacing between key centers (Y-axis)
  kp: 19 # padding (default: 19)
  ks: 19 # spread (deafult: 19)
  kcow: 14 # key cutout hole width (cherry: 14, choc: 13.8)
  kcoh: 14 # key cutout hole height (cherry: 14, choc: 13.8)
  keycw: 18 # keycap width (cherry: 18, choc: 17.5)
  keych: 18 # keycap height (cherry: 18, choc: 16.5)

  # Physical measures
  fillet_radius: 1

points:
  zones:
    matrix:
      key:
        tags:
          - key
          - keys_matrix
      anchor:
        shift: [160, -175]
        rotate: 0
      rotate: 6.5
      rows:
        R2:
          row_net: R2
        R1:
          row_net: R1
        R0:
          row_net: R0
      columns:
        C0:
          key:
            column_net: C0
            stagger: -0.5ky
        C1:
          key:
            column_net: C1
            splay: -4
            stagger: 7
            spread: ks+1.25
        C2:
          key:
            column_net: C2
            splay: -2
            stagger: 5
            spread: ks+1.25
        C3:
          key:
            column_net: C3
            stagger: -3
            splay: -2
            spread: ks+1.25
        C4:
          key:
            column_net: C4
            stagger: -5
            splay: -1
            spread: ks+1.25
    thumbs:
      key:
        tags:
          - key
          - keys_thumbs
      anchor:
        ref: matrix_C2_R2
        shift: [0, -1U]
      rows:
        R3:
          row_net: R3
      columns:
        C1:
          key:
            column_net: C1
        C2:
          key:
            column_net: C2
            splay: -2
            stagger: -3.5
            shift: [0.5, 0]
            spread: ks+0.25
        C3:
          key:
            column_net: C3
            splay: -7
            shift: [2.25, -5.75]
        C4:
          key:
            column_net: C4
            splay: -6
            stagger: -6.5
            shift: [4, 0]
outlines:
  debug_points:
    - what: rectangle
      where: true
      size: [6, 0.01]
    - what: rectangle
      where: true
      size: [0.01, 4]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [3, 0]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [0, 2]
    - what: rectangle
      where: [key]
      size: [kx, ky]
      operation: stack
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
      operation: stack
    - what: circle
      where: [screw]
      radius: 2
      operation: stack
  _switch_cutouts:
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
  _base:
    - what: rectangle
      where: [key]
      size: [kp, kp]
    - what: polygon
      operation: add
      points:
        - ref: matrix_C4_R0
          shift: [1.65kp, 0.25kp]
        - ref: thumbs_C4_R3
          shift: [0.5kp, 0.5kp]
        - ref: thumbs_C3_R3
          shift: [0, 0]
        - ref: matrix_C4_R0
          shift: [0, 0.25kp]
  pcb:
    - what: outline
      name: _base
      expand: 2.25
      # fillet: fillet_radius
  preview:
    - what: outline
      name: debug_points
    - what: rectangle
      where: [key]
      size: [keycw, keych]
      operation: stack
    - what: outline
      name: _switch_cutouts
      operation: stack
    - what: outline
      name: pcb
      operation: stack
pcbs:
  goose:
    outlines:
      main.outline: pcb
    footprints:
      switches:
        what: mx
        where: [key]
        params:
          keycaps: true
          reverse: false
          hotswap: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes:
        what: custom/combo_diode
        where: [key]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          # side: "B"
          include_smd: true
          include_tht: false
          reversible: false
        adjust:
          shift: [-7, 5.5]
          rotate: -90
      mcu:
        what: custom/xiao_ble
        # what: custom/xiao_ble_kleeb
        params:
          holes: true
          dio: true
          battery_minus: true
          nfc: false
        where:
          ref: matrix_C4_R0
          shift: [22, -3.8]
      switch_reset:
        what: custom/switch_reset
        params:
          side: "B"
          from: "GND"
          to: "RST"
        where:
          ref: matrix_C0_R0
          # shift: [32, -16]
          rotate: 90
          shift: [0, 10]
      switch_power:
        what: custom/switch_power
        where:
          ref: matrix_C4_R0
          shift: [0, 10]
          rotate: 90
        params:
          side: "B"
          from: "BAT+"
          to: "BAT_P"
      battery_pads:
        what: custom/battery_pad
        params:
          side: "B"
          pos: "BAT_P"
          neg: "BAT-"
        where:
          ref: matrix_C4_R1
          shift: [26.8, 0.8]
          rotate: 90
