units:
  # Key and keycap measures
  kx: u # spacing between key centers (X-axis)
  ky: u # spacing between key centers (Y-axis)
  kp: 19 # padding (default: 19)
  ks: 19 # spread (deafult: 19)
  kcow: 14 # key cutout hole width (cherry: 14, choc: 13.8)
  kcoh: 14 # key cutout hole height (cherry: 14, choc: 13.8)
  keycw: 18 # keycap width (cherry: 18, choc: 17.5)
  keych: 18 # keycap height (cherry: 18, choc: 16.5)
points:
  zones:
    matrix:
      key:
        tags:
          - key
      anchor:
        shift: [160, -175]
        rotate: 0
      rotate: 6.5
      rows:
        R2:
          row_net: R2
        R1:
          row_net: R1
        R0:
          row_net: R0
      columns:
        C0:
          key:
            column_net: C0
            stagger: -0.5ky
            tags:
              - col0
              - key
        C1:
          key:
            column_net: C1
            splay: -4
            stagger: 7
            spread: ks+1.25
        C2:
          key:
            column_net: C2
            splay: -2
            stagger: 5
            spread: ks+1.25
        C3:
          key:
            column_net: C3
            stagger: -3
            splay: -2
            spread: ks+1.25
        C4:
          key:
            column_net: C4
            stagger: -5
            splay: -1
            spread: ks+1.25
    thumbs:
      key:
        tags:
          - key
      anchor:
        ref: matrix_C2_R2
        shift: [0, -1U]
      rows:
        R3:
          row_net: R3
      columns:
        C1:
          key:
            column_net: C1
        C2:
          key:
            column_net: C2
            splay: -2
            stagger: -3.5
            shift: [0.5, 0]
            spread: ks+0.25
        C3:
          key:
            column_net: C3
            splay: -7
            shift: [2.25, -5.75]
        C4:
          key:
            column_net: C4
            splay: -6
            stagger: -6.5
            shift: [4, 0]
outlines:
  debug_points:
    - what: rectangle
      where: true
      size: [6, 0.01]
    - what: rectangle
      where: true
      size: [0.01, 4]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [3, 0]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [0, 2]
    - what: rectangle
      where: [key]
      size: [kx, ky]
      operation: stack
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
      operation: stack
    - what: circle
      where: [screw]
      radius: 2
      operation: stack
  _switch_cutouts:
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
  _base:
    - what: rectangle
      # where: [key]
      where: true
      bound: true
      size: [kp, kp]
    - what: polygon
      operation: add
      points:
        - ref: matrix_C4_R0
          shift: [1.65kp, 0.25kp]
        - ref: thumbs_C4_R3
          shift: [0.5kp, 0.5kp]
        - ref: thumbs_C3_R3
          shift: [0, 0]
        - ref: matrix_C4_R0
          shift: [0, 0.25kp]
  pcb:
    - what: outline
      name: _base
      expand: 2
      fillet: 0
  preview:
    - what: outline
      name: debug_points
    - what: rectangle
      where: [key]
      size: [keycw, keych]
      operation: stack
    - what: outline
      name: _switch_cutouts
      operation: stack
    - what: outline
      name: pcb
      operation: stack
pcbs:
  goose:
    outlines:
      main.outline: pcb
    footprints:
      switches:
        what: mx
        where:
          - /matrix/
          - /thumbs/
        params:
          keycaps: true
          reverse: false
          hotswap: false
          from: "{{column_net}}"
          to: "{{colrow}}"
        # adjust:
        #   rotate: 180
      diodes:
        what: custom/combo_diode
        where:
          - /matrix/
          - /thumbs/
        params:
          side: "B"
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_smd: true
          include_tht: false
          # reversible: false
        adjust:
          shift: [-7, -4.5]
          rotate: 90
      xiao_ble:
        what: custom/xiao_ble
        # what: custom/xiao_ble_smd_reversible
        params:
          side: "F"
          holes: false
          dio: false
          battery_minus: true
          nfc: false
          P2: "C4"
          P3: "R0"
          P4: "R1"
          P5: "R2"
          P6: "R3"
          P7: "C0"
          P8: "C1"
          P9: "C2"
          P10: "C3"
        where:
          ref: matrix_C4_R0
          shift: [22, -4.5]
          rotate: 270
      enc_wheel:
        what: rotary
        params:
          from: ""
          to: ""
          A: "P0"
          B: "P1"
          C: "GND"
        where:
          ref: matrix_C4_R2
          shift: [23.3, -2]
      #     rotate: 180
      switch_reset:
        what: custom/switch_reset
        params:
          side: "B"
          from: "GND"
          to: "RST"
        where:
          # ref: matrix_C4_R1
          # shift: [31.8, -1]
          # rotate: 0
          ref: matrix_C4_R0
          shift: [0, 9.7]
          rotate: 90
      # switch_power:
      #   what: custom/switch_power
      #   params:
      #     side: "B"
      #     from: "BAT_P"
      #     to: "BAT+"
      #   where:
      #     ref: matrix_C4_R0
      #     # ref: matrix_C4_R1
      #     shift: [0, 9.6]
      #     rotate: 90
      battery_connector:
        what: custom/battery_pad
        params:
          side: "B"
          pos: "BAT+"
          neg: "BAT-"
        where:
          ref: matrix_C4_R0
          shift: [23.3, -5]
          # ref: matrix_C4_R0
          # shift: [-10, 9]
          # ref: matrix_C4_R1
          # shift: [30, 3]
          rotate: 0
      mount_m2_c0_top:
        what: custom/mounting_hole
        params:
        where:
          ref.aggregate.parts:
            [matrix_C0_R0, matrix_C1_R0, matrix_C0_R1, matrix_C1_R1]
      mount_m2_c1_bottom:
        what: custom/mounting_hole
        params:
        where:
          ref.aggregate.parts:
            [matrix_C0_R1, matrix_C1_R1, matrix_C0_R2, matrix_C1_R2]
      mount_m2_c3_top:
        what: custom/mounting_hole
        params:
        where:
          ref.aggregate.parts: [matrix_C3_R0, matrix_C4_R0]
          shift: [0, -1]
      mount_m2_c2_bottom:
        what: custom/mounting_hole
        params:
        where:
          ref.aggregate.parts: [thumbs_C1_R3, matrix_C3_R2]
          shift: [0, -2]
      mount_m2_c4_bottom:
        what: custom/mounting_hole
        params:
        where:
          ref.aggregate.parts: [matrix_C4_R2, thumbs_C3_R3]
          shift: [8, 0]
      txt_peace_1:
        what: custom/text
        params:
          side: "F"
          text: "PEACE"
        where:
          ref: matrix_C0_R2
          shift: [0, -10.4]
      txt_peace_2:
        what: custom/text
        params:
          side: "F"
          text: "WAS"
        where:
          ref: matrix_C1_R2
          shift: [0, -10.4]
      txt_peace_3:
        what: custom/text
        params:
          side: "F"
          text: "NEVER"
        where:
          ref: thumbs_C1_R3
          shift: [0, -10.4]
      txt_peace_4:
        what: custom/text
        params:
          side: "F"
          text: "AN"
        where:
          ref: thumbs_C2_R3
          shift: [0, -10.4]
      txt_peace_5:
        what: custom/text
        params:
          side: "F"
          text: "OPTION!"
        where:
          ref: thumbs_C3_R3
          shift: [0, -10.4]
      txt_peace_6:
        what: custom/text
        params:
          side: "F"
          text: "[BONK!]"
        where:
          ref: thumbs_C4_R3
          shift: [0, -10.4]
