units:
  # Key and keycap measures
  kx: u # spacing between key centers (X-axis)
  ky: u # spacing between key centers (Y-axis)
  kp: 19 # padding (default: 19)
  ks: 19 # spread (deafult: 19)
  kcow: 14 # key cutout hole width (cherry: 14, choc: 13.8)
  kcoh: 14 # key cutout hole height (cherry: 14, choc: 13.8)
  keycw: 18 # keycap width (cherry: 18, choc: 17.5)
  keych: 18 # keycap height (cherry: 18, choc: 16.5)
points:
  zones:
    matrix:
      key:
        tags:
          - key
      anchor:
        shift: [160, -175]
        rotate: 0
      rotate: 6.5
      rows:
        R2:
          row_net: R2
        R1:
          row_net: R1
        R0:
          row_net: R0
      columns:
        C0:
          key:
            column_net: C0
            stagger: -0.5ky
            tags:
              - col0
              - key
        C1:
          key:
            column_net: C1
            splay: -4
            stagger: 7
            spread: ks+1.25
        C2:
          key:
            column_net: C2
            splay: -2
            stagger: 5
            spread: ks+1.25
        C3:
          key:
            column_net: C3
            stagger: -3
            splay: -2
            spread: ks+1.25
        C4:
          key:
            column_net: C4
            stagger: -5
            splay: -1
            spread: ks+1.25
    thumbs:
      key:
        tags:
          - key
      anchor:
        ref: matrix_C2_R2
        shift: [0, -1U]
      rows:
        R3:
          row_net: R3
      columns:
        C1:
          key:
            column_net: C1
            stagger: -1
        C2:
          key:
            column_net: C2
            splay: -2
            stagger: -2.5
            shift: [0.5, 0]
            spread: ks+0.25
        C3:
          key:
            column_net: C3
            splay: -7
            shift: [2.25, -5.75]
        C4:
          key:
            column_net: C4
            splay: -6
            stagger: -6.5
            shift: [4, 0]
    mountscrew_c0_top:
      anchor:
        ref.aggregate.parts:
          [matrix_C0_R0, matrix_C1_R0, matrix_C0_R1, matrix_C1_R1]
        #shift: [-11, 0]
      columns.screw.key.tags: [screw]
    mountscrew_c1_bottom:
      anchor:
        ref.aggregate.parts:
          [matrix_C0_R1, matrix_C1_R1, matrix_C0_R2, matrix_C1_R2]
      columns.screw.key.tags: [screw]
    mountscrew_c3_top:
      anchor:
        ref.aggregate.parts: [matrix_C2_R0, matrix_C3_R0]
        shift: [0, -8]
      columns.screw.key.tags: [screw]
    mountscrew_c2_bottom:
      anchor:
        ref.aggregate.parts: [matrix_C2_R2, matrix_C3_R2]
        shift: [0, -8]
      columns.screw.key.tags: [screw]
    mountscrew_c4_bottom:
      anchor:
        ref.aggregate.parts: [thumbs_C3_R3, thumbs_C4_R3]
        shift: [0, 8]
      columns.screw.key.tags: [screw]
outlines:
  debug_points:
    - what: rectangle
      where: true
      size: [6, 0.01]
    - what: rectangle
      where: true
      size: [0.01, 4]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [3, 0]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [0, 2]
    - what: rectangle
      where: [key]
      size: [kx, ky]
      operation: stack
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
      operation: stack
    - what: circle
      where: [screw]
      radius: 2
      operation: stack
  _switch_cutouts:
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
  _base:
    - what: rectangle
      where: [key]
      bound: true
      size: [kp, kp]
  _pcb_plate:
    - what: outline
      name: _base
    - what: polygon
      operation: add
      points:
        - ref: thumbs_C4_R3
          shift: [0, 0.5kp]
        - ref: matrix_C4_R2
          shift: [0, -9]
        - ref: thumbs_C3_R3
          shift: [0, 0]
    - what: outline
      name: _pcb_plate
      expand: 2
    - what: outline
      name: _switch_cutouts
      operation: subtract
  _pcb_keyboard:
    - what: outline
      name: _base
    - what: polygon
      operation: add
      points:
        - ref: matrix_C4_R0
          shift: [1.65kp, 0.25kp]
        - ref: thumbs_C4_R3
          shift: [0.5kp, 0.5kp]
        - ref: thumbs_C3_R3
          shift: [0, 0]
        - ref: matrix_C4_R0
          shift: [0, 0.25kp]
    - what: outline
      name: _pcb_keyboard
      expand: 2
      fillet: 0
  plate:
    - what: outline
      name: _pcb_plate
  pcb:
    - what: outline
      name: _pcb_keyboard
  preview:
    - what: outline
      name: debug_points
    - what: rectangle
      where: [key]
      size: [keycw, keych]
      operation: stack
    - what: outline
      name: _switch_cutouts
      operation: stack
    - what: outline
      name: pcb
      operation: stack
pcbs:
  plate:
    outlines:
      main.outline: plate
    footprints:
      screws:
        what: custom/mounting_hole
        params:
          drill: 4.3
          outline: 0.4
        where: [screw]
  bottom:
    outlines:
      main.outline: pcb
    footprints:
      screws:
        what: custom/mounting_hole
        params:
        where: [screw]
  goose:
    outlines:
      main.outline: pcb
    footprints:
      switches:
        what: custom/mx
        where:
          - /matrix/
          - /thumbs/
        params:
          keycaps: true
          reverse: true
          hotswap: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes_back:
        what: custom/combo_diode
        where:
          - /matrix/
          - /thumbs/
        params:
          side: "B"
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_smd: true
          include_tht: false
          reversible: false
        adjust:
          rotate: 180
          shift: [0, -4.5]
          # rotate: 65
          # shift: [-5.75, 4.5]
      diodes_front:
        what: custom/combo_diode
        where:
          - /matrix/
          - /thumbs/
        params:
          side: "F"
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_smd: true
          include_tht: false
          reversible: false
        adjust:
          rotate: 180
          shift: [0, -4.5]
          # shift: [-5.75, 4.5]
          # rotate: 115
          # shift: [5.75, 4.5]
      xiao_ble:
        what: custom/xiao_ble_smd_reversible
        params:
          # reversible pins
          D0: "C0"
          D1: "C1"
          D2: "C2"
          D3: "C3"
          D4: "C4"
          D5: "R0"
          D6: "R1"
          D7: "ENCA"
          D8: "ENCB"
          D9: "R3"
          D10: "R2"
        where:
          ref: matrix_C4_R0
          shift: [22, -4]
      enc_wheel:
        what: rotary
        params:
          from: ""
          to: ""
          A: "ENCA"
          B: "ENCB"
          C: "GND"
        where:
          ref: matrix_C4_R2
          shift: [23, -1]
          rotate: 270
      battery_pads:
        what: custom/pads
        params:
          reverse: true
          net_1: "BAT+"
          net_2: "GND"
          label_1: "+"
          label_2: ""
          label_at_bottom: true
          space: 1.25
        where:
          ref: matrix_C4_R1
          shift: [15, 1]
          rotate: 0
      screws:
        what: custom/mounting_hole
        params:
        where: [screw]
      txt_version:
        what: custom/text
        params:
          side: "B"
          text: "gooses v0.9b"
        where:
          ref: thumbs_C4_R3
          shift: [8, 0]
          rotate: 90
      # txt_order_number:
      #   what: custom/text
      #   params:
      #     side: "F"
      #     text: "JLCJLCJLCJLC"
      #   where:
      #     ref: matrix_C1_R2
      #     shift: [0, -6]
      txt_this_side_up:
        what: custom/text
        params:
          text: "↑gås upp↑"
          reverse: false
        where:
          ref: matrix_C4_R0
          shift: [22, -15.5]
      txt_this_side_down:
        what: custom/text
        params:
          side: "B"
          text: "↓gås ner↓"
          reverse: false
        where:
          ref: matrix_C4_R0
          shift: [22, -15.5]
