units:
  # Key and keycap measures
  kx: u # spacing between key centers (X-axis)
  ky: u # spacing between key centers (Y-axis)
  kp: 19 # padding (default: 19)
  ks: 19 # spread (deafult: 19)
  kcow: 14 # key cutout hole width (cherry: 14, choc: 13.8)
  kcoh: 14 # key cutout hole height (cherry: 14, choc: 13.8)
  keycw: 18 # keycap width (cherry: 18, choc: 17.5)
  keych: 18 # keycap height (cherry: 18, choc: 16.5)
  mirror_distance: 2.5kx
points:
  mirror: &mirror
    ref: thumbs_C4_R3
    distance: mirror_distance
  zones:
    matrix:
      key:
        bind: 1
        tags:
          - key
      anchor:
        shift: [150, -175]
      #   rotate: 0
      # rotate: 6.5
      rows:
        R2:
          row_net: R2
          mirror.row_net: rR2
        R1:
          row_net: R1
          mirror.row_net: rR1
        R0:
          row_net: R0
          mirror.row_net: rR0
      columns:
        C0:
          key:
            column_net: C0
            mirror.column_net: rC0
            stagger: -0.5ky
            tags:
              - col0
              - key
        C1:
          key:
            column_net: C1
            mirror.column_net: rC1
            splay: -4
            stagger: 7
            spread: ks+1.25
        C2:
          key:
            column_net: C2
            mirror.column_net: rC2
            splay: -2
            stagger: 5
            spread: ks+1.25
        C3:
          key:
            column_net: C3
            mirror.column_net: rC3
            stagger: -3
            splay: -2
            spread: ks+1.25
        C4:
          key:
            column_net: C4
            mirror.column_net: rC4
            stagger: -5
            splay: -1
            spread: ks+1.25
    thumbs:
      key:
        bind: 1
        tags:
          - key
      anchor:
        ref: matrix_C2_R2
        shift: [0, -1U]
      rows:
        R3:
          row_net: R3
          mirror.row_net: rR3
      columns:
        C1:
          key:
            column_net: C1
            mirror.column_net: rC1
            stagger: -1
        C2:
          key:
            column_net: C2
            mirror.column_net: rC2
            splay: -2
            stagger: -2.5
            shift: [0.5, 0]
            spread: ks+0.25
        C3:
          key:
            column_net: C3
            mirror.column_net: rC3
            splay: -7
            shift: [2.25, -5.75]
        C4:
          key:
            column_net: C4
            mirror.column_net: rC4
            splay: -6
            stagger: -6.5
            shift: [4, 0]
    mountscrew_c0_top:
      anchor:
        ref.aggregate.parts:
          [matrix_C0_R0, matrix_C1_R0, matrix_C0_R1, matrix_C1_R1]
      columns.screw.key.tags: [screw]
    mountscrew_c1_bottom:
      anchor:
        ref.aggregate.parts:
          [matrix_C0_R1, matrix_C1_R1, matrix_C0_R2, matrix_C1_R2]
      columns.screw.key.tags: [screw]
    mountscrew_c3_top:
      anchor:
        ref.aggregate.parts: [matrix_C2_R0, matrix_C3_R0]
        shift: [0, -8]
      columns.screw.key.tags: [screw]
    mountscrew_c2_bottom:
      anchor:
        ref.aggregate.parts: [matrix_C2_R2, matrix_C3_R2]
        shift: [0, -10.5]
      columns.screw.key.tags: [screw]
    mountscrew_c4_bottom:
      anchor:
        ref.aggregate.parts: [thumbs_C3_R3, thumbs_C4_R3]
        shift: [0, 8]
      columns.screw.key.tags: [screw]
outlines:
  # debug_points:
  #   - what: rectangle
  #     where: true
  #     size: [6, 0.01]
  #   - what: rectangle
  #     where: true
  #     size: [0.01, 4]
  #   - what: circle
  #     where: true
  #     radius: 0.4
  #     adjust:
  #       shift: [3, 0]
  #   - what: circle
  #     where: true
  #     radius: 0.4
  #     adjust:
  #       shift: [0, 2]
  #   - what: rectangle
  #     where: [key]
  #     size: [kx, ky]
  #     operation: stack
  #   - what: rectangle
  #     where: [key]
  #     size: [kcow, kcoh]
  #     operation: stack
  #   - what: circle
  #     where: [screw]
  #     radius: 2
  #     operation: stack
  _switch_cutouts:
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
  _base:
    - what: rectangle
      where: [key]
      bound: true
      size: [kp, kp]
  _pcb_plate:
    - what: outline
      name: _base
    - what: polygon
      operation: add
      points:
        - ref: thumbs_C4_R3
          shift: [0, 0.5kp]
        - ref: matrix_C4_R2
          shift: [0, -9]
        - ref: thumbs_C3_R3
          shift: [0, 0]
    - what: outline
      name: _pcb_plate
      expand: 2
    - what: outline
      name: _switch_cutouts
      operation: subtract
  _pcb_keyboard:
    - what: outline
      name: _base
    - what: polygon
      operation: add
      points:
        - ref: matrix_C4_R0
          shift: [1.65kp, 0.25kp]
        - ref: thumbs_C4_R3
          shift: [0.56kp, 0.5kp]
        - ref: thumbs_C3_R3
          shift: [0, 0]
        - ref: matrix_C4_R0
          shift: [0, 0.25kp]
    - what: polygon
      operation: add
      points:
        - ref: mirror_matrix_C4_R0
          shift: [1.65kp, 0.25kp]
        - ref: mirror_thumbs_C4_R3
          shift: [0.56kp, 0.5kp]
        - ref: mirror_thumbs_C3_R3
          shift: [0, 0]
        - ref: mirror_matrix_C4_R0
          shift: [0, 0.25kp]
    - what: outline
      name: _pcb_keyboard
      expand: 2
      fillet: 0
  plate:
    - what: outline
      name: _pcb_plate
  pcb:
    - what: outline
      name: _pcb_keyboard
  # preview:
  #   - what: outline
  #     name: debug_points
  #   - what: rectangle
  #     where: [key]
  #     size: [keycw, keych]
  #     operation: stack
  #   - what: outline
  #     name: _switch_cutouts
  #     operation: stack
  #   - what: outline
  #     name: pcb
  #     operation: stack
pcbs:
  plate:
    outlines:
      main.outline: plate
    footprints:
      screws:
        what: custom/mounting_hole
        params:
        where: [screw]
      txt_peace_1:
        what: custom/text
        params:
          side: "F"
          text: "PEACE"
        where:
          ref: matrix_C0_R2
          shift: [0, -10.4]
      txt_peace_2:
        what: custom/text
        params:
          side: "F"
          text: "WAS"
        where:
          ref: matrix_C1_R2
          shift: [0, -10.4]
      txt_peace_3:
        what: custom/text
        params:
          side: "F"
          text: "NEVER"
        where:
          ref: thumbs_C1_R3
          shift: [0, -10.4]
      txt_peace_4:
        what: custom/text
        params:
          side: "F"
          text: "AN"
        where:
          ref: thumbs_C2_R3
          shift: [0, -10.4]
      txt_peace_5:
        what: custom/text
        params:
          side: "F"
          text: "OPTION!"
        where:
          ref: thumbs_C3_R3
          shift: [0, -10.4]
      txt_peace_6:
        what: custom/text
        params:
          side: "F"
          text: "[BONK!]"
        where:
          ref: thumbs_C4_R3
          shift: [0, -10.4]
  goose:
    outlines:
      main.outline: pcb
    footprints:
      switches:
        what: custom/mx
        where:
          - /matrix/
          - /thumbs/
        params:
          keycaps: true
          reverse: false
          hotswap: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes_left:
        what: custom/combo_diode
        where:
          - /^matrix_.*/
          - /^thumbs_.*/
        params:
          side: "B"
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_smd: true
          include_tht: false
          reversible: false
        adjust:
          rotate: 90
          shift: [-7, -4.5]
      diodes_right:
        what: custom/combo_diode
        where:
          - /^mirror.matrix_.*/
          - /^mirror.thumbs_.*/
        params:
          side: "B"
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_smd: true
          include_tht: false
          reversible: false
        adjust:
          rotate: 270
          shift: [7, -4.5]
      xiao_ble_left:
        what: custom/xiao_ble
        params:
          side: "F"
          holes: false
          dio: false
          battery_minus: false
          nfc: false
          P10: "R2"
          P9: "R3"
          P8: "RB"
          P7: "RA"
          P6: "R1"
          P5: "R0"
          P4: "C4"
          P3: "C3"
          P2: "C2"
          P1: "C1"
          P0: "C0"
        where:
          ref: matrix_C4_R0
          shift: [22, -4]
      xiao_ble_right:
        what: custom/xiao_ble
        params:
          side: "F"
          holes: false
          dio: false
          battery_minus: false
          nfc: false
          # P10: "R2"
          # P9: "R3"
          # P6: "R1"
          # P5: "R0"
          # P4: "C4"
          # P3: "C3"
          # P2: "C2"
          # P1: "C1"
          # P0: "C0"
          # P6: "rRB"
          # P5: "rRA"
          P4: "rR3"
          P3: "rR2"
        where:
          ref: mirror_matrix_C4_R0
          shift: [22, -4]
      enc_wheel_left:
        what: rotary
        params:
          from: ""
          to: ""
          A: "RA"
          B: "RB"
          C: "GND"
        where:
          ref: matrix_C4_R2
          shift: [22, -1]
          rotate: 270
      enc_wheel_right:
        what: rotary
        params:
          from: ""
          to: ""
          A: "rRA"
          B: "rRB"
          C: "GND"
        where:
          ref: mirror_matrix_C4_R2
          shift: [22, -1]
          rotate: 90
      battery_connector_left:
        what: custom/battery_pad
        params:
          side: "B"
          pos: "BATP"
          neg: "GND"
        where:
          ref: matrix_C4_R0
          shift: [18.5, -7]
          rotate: 0
      battery_connector_right:
        what: custom/battery_pad
        params:
          side: "B"
          pos: "BATP"
          neg: "GND"
        where:
          ref: mirror_matrix_C4_R0
          shift: [25.5, -7]
          rotate: 0
      screws:
        what: custom/mounting_hole
        params:
        where: [screw]
      txt_version:
        what: custom/text
        params:
          side: "B"
          text: "gooses v0.8a"
        where:
          ref: thumbs_C4_R3
          shift: [8, 0]
          rotate: 90
      txt_order_number:
        what: custom/text
        params:
          side: "F"
          text: "JLCJLCJLCJLC"
        where:
          ref: matrix_C1_R2
          shift: [0, -6]
      txt_this_side_up_left:
        what: custom/text
        params:
          text: "↑gås upp↑"
          reverse: false
        where:
          ref: matrix_C4_R0
          shift: [22, -15.5]
      txt_this_side_up_right:
        what: custom/text
        params:
          text: "↑gås upp↑"
          reverse: false
        where:
          ref: mirror_matrix_C4_R0
          shift: [22, -15.5]
      txt_this_side_down_left:
        what: custom/text
        params:
          side: "B"
          text: "↓gås ner↓"
          reverse: false
        where:
          ref: matrix_C4_R0
          shift: [22, -15.5]
      txt_this_side_down_right:
        what: custom/text
        params:
          side: "B"
          text: "↓gås ner↓"
          reverse: false
        where:
          ref: mirror_matrix_C4_R0
          shift: [22, -15.5]
      txt_reset_left:
        what: custom/text
        params:
          text: "!#@"
          reverse: true
        where:
          ref: matrix_C4_R0
          shift: [22, 0.6]
      txt_reset_right:
        what: custom/text
        params:
          text: "!#@"
          reverse: true
        where:
          ref: mirror_matrix_C4_R0
          shift: [22, 0.6]
