units:
  # Key and keycap measures
  kx: cx # spacing between key centers (X-axis)
  ky: cy # spacing between key centers (Y-axis)  kp: 19 # padding (default: 19)
  ks: 19 # spread (deafult: 19)
  kp: cx
  kcow: 13.8 # key cutout hole width (cherry: 14, choc: 13.8)
  kcoh: 13.8 # key cutout hole height (cherry: 14, choc: 13.8)
  keycw: 17.5 # keycap width (cherry: 18, choc: 17.5)
  keych: 16.5 # keycap height (cherry: 18, choc: 16.5)
  $default_autobind: 5
points:
  zones:
    matrix:
      key:
        padding: cy
        spread: ks
        tags:
          - key
      anchor:
        shift: [160, -175]
        rotate: 0
      rotate: 6.5
      rows:
        R2:
          row_net: R2
        R1:
          row_net: R1
        R0:
          row_net: R0
      columns:
        C0:
          key:
            column_net: C0
            stagger: 6
            splay: 0
        C1:
          key:
            column_net: C1
            splay: -4
            stagger: 7
        C2:
          key:
            column_net: C2
            splay: -2
            stagger: 5
        C3:
          key:
            column_net: C3
            stagger: -3
            splay: -2
        C4:
          key:
            column_net: C4
            stagger: -5
            splay: -1
    thumbs:
      key:
        padding: cy
        spread: ks
        tags:
          - key
      anchor:
        ref: matrix_C2_R2
        shift: [0.6cx, -1.2cy]
      rows:
        R3:
          row_net: R3
      columns:
        C1:
          key:
            bind: [5,5,0,0]
            column_net: C1
            stagger: -1
            #shift: [-0, 0cy]
            splay: -2
        C2:
          key:
            bind: [5,5,0,0]
            column_net: C2
            splay: -8
            stagger: -2
            shift: [0.20cy, -0.15cy]
        C3:
          key:
            bind: [1,0,0,0]
            column_net: C3
            splay: -3
            stagger: -3
            shift: [0.35cy, 0.05cy]
            rotate: 270
    mountscrew_c0_top:
      anchor:
        ref.aggregate.parts:
          [matrix_C0_R0, matrix_C1_R0, matrix_C0_R1, matrix_C1_R1]
        shift: [0, 3]
      columns.screw.key.tags: [screw]
    mountscrew_c1_bottom:
      anchor:
        ref.aggregate.parts:
          [matrix_C0_R1, matrix_C1_R1, matrix_C0_R2, matrix_C1_R2]
      columns.screw.key.tags: [screw]
    mountscrew_c3_top:
      anchor:
        ref.aggregate.parts: [matrix_C2_R0, matrix_C3_R0]
        shift: [0, -3]
      columns.screw.key.tags: [screw]
    mountscrew_c2_bottom:
      anchor:
        ref.aggregate.parts: [matrix_C2_R2, matrix_C3_R2]
        shift: [0.1, -10]
      columns.screw.key.tags: [screw]
    mountscrew_c4_bottom:
      anchor:
        ref.aggregate.parts: [thumbs_C3_R3, thumbs_C2_R3, matrix_C4_R2]
        shift: [2, -2.8]
      columns.screw.key.tags: [screw]
outlines:
  # debug_points:
  #   - what: rectangle
  #     where: true
  #     size: [6, 0.01]
  #   - what: rectangle
  #     where: true
  #     size: [0.01, 4]
  #   - what: circle
  #     where: true
  #     radius: 0.4
  #     adjust:
  #       shift: [3, 0]
  #   - what: circle
  #     where: true
  #     radius: 0.4
  #     adjust:
  #       shift: [0, 2]
  #   - what: rectangle
  #     where: [key]
  #     size: [cx, cy]
  #     operation: stack
  #   - what: rectangle
  #     where: [key]
  #     size: [kcow, kcoh]
  #     operation: stack
  #   - what: circle
  #     where: [screw]
  #     radius: 2
  #     operation: stack
  # _switch_cutouts:
  #   - what: rectangle
  #     where: [key]
  #     size: [kcow, kcoh]
  _base:
    - what: rectangle
      where: [key]
      bound: true
      size: [cx, cy]
  _pcb_keyboard:
    - what: outline
      name: _base
    - what: polygon
      operation: add
      points:
        - ref: matrix_C4_R0
          shift: [1.65cx, 0.25cy]
        - ref: thumbs_C3_R3
          shift: [-0.5cx, 0.56cy]
        - ref: thumbs_C3_R3
          shift: [0.5cx, 0]
        - ref: matrix_C4_R0
          shift: [0, 0.25cy]
    - what: outline
      name: _pcb_keyboard
      expand: 2
      fillet: 1
  pcb:
    - what: outline
      name: _pcb_keyboard
  # preview:
  #   - what: outline
  #     name: debug_points
  #   - what: rectangle
  #     where: [key]
  #     size: [keycw, keych]
  #     operation: stack
  #   - what: outline
  #     name: _switch_cutouts
  #     operation: stack
  #   - what: outline
  #     name: pcb
  #     operation: stack
pcbs:
  bottom_choc:
    outlines:
      main.outline: pcb
    footprints:
      screws:
        what: custom/mounting_hole
        params:
        where: [screw]
  goose_choc:
    outlines:
      main.outline: pcb
    footprints:
      switches:
        what: choc
        where:
          - /matrix/
          - /thumbs/
        params:
          keycaps: true
          reverse: true
          hotswap: false
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes_back:
        what: custom/combo_diode
        where:
          - /matrix/
          - /thumbs/
        params:
          side: "B"
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_smd: true
          include_tht: false
          reversible: false
        adjust:
          rotate: 180
          shift: [0, -4.5]
          # rotate: 65
          # shift: [-5.75, 4.5]
      diodes_front:
        what: custom/combo_diode
        where:
          - /matrix/
          - /thumbs/
        params:
          side: "F"
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_smd: true
          include_tht: false
          reversible: false
        adjust:
          rotate: 180
          shift: [0, -4.5]
          # shift: [-5.75, 4.5]
          # rotate: 115
          # shift: [5.75, 4.5]
      xiao_ble:
        what: custom/xiao_ble_smd_reversible
        params:
          # reversible pins
          D0: "C0"
          D1: "C1"
          D2: "C2"
          D3: "C3"
          D4: "C4"
          D5: "R0"
          D6: "R1"
          D7: "ENCA"
          D8: "ENCB"
          D9: "R3"
          D10: "R2"
        where:
          ref: matrix_C4_R0
          shift: [20.5, -4.25]
      enc_wheel:
        what: rotary
        params:
          from: ""
          to: ""
          A: "ENCA"
          B: "ENCB"
          C: "GND"
        where:
          ref: matrix_C4_R2
          shift: [21, -1]
          rotate: 268
      battery_pads:
        what: custom/pads
        params:
          reverse: true
          net_1: "BAT+"
          net_2: "GND"
          label_1: "+"
          label_2: ""
          label_at_bottom: true
          space: 1.25
        where:
          ref: matrix_C4_R1
          shift: [13.5, 0.3]
          rotate: 0
      screws:
        what: custom/mounting_hole
        params:
        where: [screw]
      txt_version:
        what: custom/text
        params:
          side: "B"
          text: "gooses v0.91c"
        where:
          ref: thumbs_C3_R3
          shift: [8, 0]
          rotate: 90
      # txt_order_number:
      #   what: custom/text
      #   params:
      #     side: "F"
      #     text: "JLCJLCJLCJLC"
      #   where:
      #     ref: matrix_C1_R2
      #     shift: [0, -6]
      txt_this_side_up:
        what: custom/text
        params:
          text: "↑gås upp↑"
          reverse: false
        where:
          ref: matrix_C4_R0
          shift: [21, -15.8]
      txt_this_side_down:
        what: custom/text
        params:
          side: "B"
          text: "↓gås ner↓"
          reverse: false
        where:
          ref: matrix_C4_R0
          shift: [21, -15.8]

