file_format: "1"
id: goose
name: Flying Goose
type: shield
url: https://github.com/Pipshag/goosekb
requires:
  - seeeduino_xiao_ble
features:
  - keys
  - encoder
siblings:
  - goose_left
  - goose_right
